// Code generated by mockery. DO NOT EDIT.

package contracts

import (
	contracts "github.com/goravel/inertia/contracts"
	http "github.com/goravel/framework/contracts/http"

	mock "github.com/stretchr/testify/mock"

	validation "github.com/goravel/framework/contracts/validation"
)

// Inertia is an autogenerated mock type for the Inertia type
type Inertia struct {
	mock.Mock
}

type Inertia_Expecter struct {
	mock *mock.Mock
}

func (_m *Inertia) EXPECT() *Inertia_Expecter {
	return &Inertia_Expecter{mock: &_m.Mock}
}

// Always provides a mock function with given fields: ctx, key, fn
func (_m *Inertia) Always(ctx http.Context, key string, fn func() interface{}) {
	_m.Called(ctx, key, fn)
}

// Inertia_Always_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Always'
type Inertia_Always_Call struct {
	*mock.Call
}

// Always is a helper method to define mock.On call
//   - ctx http.Context
//   - key string
//   - fn func() interface{}
func (_e *Inertia_Expecter) Always(ctx interface{}, key interface{}, fn interface{}) *Inertia_Always_Call {
	return &Inertia_Always_Call{Call: _e.mock.On("Always", ctx, key, fn)}
}

func (_c *Inertia_Always_Call) Run(run func(ctx http.Context, key string, fn func() interface{})) *Inertia_Always_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.Context), args[1].(string), args[2].(func() interface{}))
	})
	return _c
}

func (_c *Inertia_Always_Call) Return() *Inertia_Always_Call {
	_c.Call.Return()
	return _c
}

func (_c *Inertia_Always_Call) RunAndReturn(run func(http.Context, string, func() interface{})) *Inertia_Always_Call {
	_c.Run(run)
	return _c
}

// ClearHistory provides a mock function with given fields: ctx
func (_m *Inertia) ClearHistory(ctx http.Context) {
	_m.Called(ctx)
}

// Inertia_ClearHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearHistory'
type Inertia_ClearHistory_Call struct {
	*mock.Call
}

// ClearHistory is a helper method to define mock.On call
//   - ctx http.Context
func (_e *Inertia_Expecter) ClearHistory(ctx interface{}) *Inertia_ClearHistory_Call {
	return &Inertia_ClearHistory_Call{Call: _e.mock.On("ClearHistory", ctx)}
}

func (_c *Inertia_ClearHistory_Call) Run(run func(ctx http.Context)) *Inertia_ClearHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.Context))
	})
	return _c
}

func (_c *Inertia_ClearHistory_Call) Return() *Inertia_ClearHistory_Call {
	_c.Call.Return()
	return _c
}

func (_c *Inertia_ClearHistory_Call) RunAndReturn(run func(http.Context)) *Inertia_ClearHistory_Call {
	_c.Run(run)
	return _c
}

// DeepMerge provides a mock function with given fields: ctx, key, fn, matchOn
func (_m *Inertia) DeepMerge(ctx http.Context, key string, fn func() interface{}, matchOn ...string) {
	_va := make([]interface{}, len(matchOn))
	for _i := range matchOn {
		_va[_i] = matchOn[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, key, fn)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// Inertia_DeepMerge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeepMerge'
type Inertia_DeepMerge_Call struct {
	*mock.Call
}

// DeepMerge is a helper method to define mock.On call
//   - ctx http.Context
//   - key string
//   - fn func() interface{}
//   - matchOn ...string
func (_e *Inertia_Expecter) DeepMerge(ctx interface{}, key interface{}, fn interface{}, matchOn ...interface{}) *Inertia_DeepMerge_Call {
	return &Inertia_DeepMerge_Call{Call: _e.mock.On("DeepMerge",
		append([]interface{}{ctx, key, fn}, matchOn...)...)}
}

func (_c *Inertia_DeepMerge_Call) Run(run func(ctx http.Context, key string, fn func() interface{}, matchOn ...string)) *Inertia_DeepMerge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(http.Context), args[1].(string), args[2].(func() interface{}), variadicArgs...)
	})
	return _c
}

func (_c *Inertia_DeepMerge_Call) Return() *Inertia_DeepMerge_Call {
	_c.Call.Return()
	return _c
}

func (_c *Inertia_DeepMerge_Call) RunAndReturn(run func(http.Context, string, func() interface{}, ...string)) *Inertia_DeepMerge_Call {
	_c.Run(run)
	return _c
}

// Defer provides a mock function with given fields: ctx, key, fn, group
func (_m *Inertia) Defer(ctx http.Context, key string, fn func() interface{}, group ...string) {
	_va := make([]interface{}, len(group))
	for _i := range group {
		_va[_i] = group[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, key, fn)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// Inertia_Defer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Defer'
type Inertia_Defer_Call struct {
	*mock.Call
}

// Defer is a helper method to define mock.On call
//   - ctx http.Context
//   - key string
//   - fn func() interface{}
//   - group ...string
func (_e *Inertia_Expecter) Defer(ctx interface{}, key interface{}, fn interface{}, group ...interface{}) *Inertia_Defer_Call {
	return &Inertia_Defer_Call{Call: _e.mock.On("Defer",
		append([]interface{}{ctx, key, fn}, group...)...)}
}

func (_c *Inertia_Defer_Call) Run(run func(ctx http.Context, key string, fn func() interface{}, group ...string)) *Inertia_Defer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(http.Context), args[1].(string), args[2].(func() interface{}), variadicArgs...)
	})
	return _c
}

func (_c *Inertia_Defer_Call) Return() *Inertia_Defer_Call {
	_c.Call.Return()
	return _c
}

func (_c *Inertia_Defer_Call) RunAndReturn(run func(http.Context, string, func() interface{}, ...string)) *Inertia_Defer_Call {
	_c.Run(run)
	return _c
}

// EncryptHistory provides a mock function with given fields: ctx
func (_m *Inertia) EncryptHistory(ctx http.Context) {
	_m.Called(ctx)
}

// Inertia_EncryptHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EncryptHistory'
type Inertia_EncryptHistory_Call struct {
	*mock.Call
}

// EncryptHistory is a helper method to define mock.On call
//   - ctx http.Context
func (_e *Inertia_Expecter) EncryptHistory(ctx interface{}) *Inertia_EncryptHistory_Call {
	return &Inertia_EncryptHistory_Call{Call: _e.mock.On("EncryptHistory", ctx)}
}

func (_c *Inertia_EncryptHistory_Call) Run(run func(ctx http.Context)) *Inertia_EncryptHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.Context))
	})
	return _c
}

func (_c *Inertia_EncryptHistory_Call) Return() *Inertia_EncryptHistory_Call {
	_c.Call.Return()
	return _c
}

func (_c *Inertia_EncryptHistory_Call) RunAndReturn(run func(http.Context)) *Inertia_EncryptHistory_Call {
	_c.Run(run)
	return _c
}

// Error provides a mock function with given fields: ctx, key, value
func (_m *Inertia) Error(ctx http.Context, key string, value interface{}) {
	_m.Called(ctx, key, value)
}

// Inertia_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type Inertia_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - ctx http.Context
//   - key string
//   - value interface{}
func (_e *Inertia_Expecter) Error(ctx interface{}, key interface{}, value interface{}) *Inertia_Error_Call {
	return &Inertia_Error_Call{Call: _e.mock.On("Error", ctx, key, value)}
}

func (_c *Inertia_Error_Call) Run(run func(ctx http.Context, key string, value interface{})) *Inertia_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.Context), args[1].(string), args[2].(interface{}))
	})
	return _c
}

func (_c *Inertia_Error_Call) Return() *Inertia_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *Inertia_Error_Call) RunAndReturn(run func(http.Context, string, interface{})) *Inertia_Error_Call {
	_c.Run(run)
	return _c
}

// Flash provides a mock function with given fields: ctx, data
func (_m *Inertia) Flash(ctx http.Context, data map[string]interface{}) {
	_m.Called(ctx, data)
}

// Inertia_Flash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Flash'
type Inertia_Flash_Call struct {
	*mock.Call
}

// Flash is a helper method to define mock.On call
//   - ctx http.Context
//   - data map[string]interface{}
func (_e *Inertia_Expecter) Flash(ctx interface{}, data interface{}) *Inertia_Flash_Call {
	return &Inertia_Flash_Call{Call: _e.mock.On("Flash", ctx, data)}
}

func (_c *Inertia_Flash_Call) Run(run func(ctx http.Context, data map[string]interface{})) *Inertia_Flash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.Context), args[1].(map[string]interface{}))
	})
	return _c
}

func (_c *Inertia_Flash_Call) Return() *Inertia_Flash_Call {
	_c.Call.Return()
	return _c
}

func (_c *Inertia_Flash_Call) RunAndReturn(run func(http.Context, map[string]interface{})) *Inertia_Flash_Call {
	_c.Run(run)
	return _c
}

// FlashErrors provides a mock function with given fields: ctx, errors
func (_m *Inertia) FlashErrors(ctx http.Context, errors validation.Errors) {
	_m.Called(ctx, errors)
}

// Inertia_FlashErrors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FlashErrors'
type Inertia_FlashErrors_Call struct {
	*mock.Call
}

// FlashErrors is a helper method to define mock.On call
//   - ctx http.Context
//   - errors validation.Errors
func (_e *Inertia_Expecter) FlashErrors(ctx interface{}, errors interface{}) *Inertia_FlashErrors_Call {
	return &Inertia_FlashErrors_Call{Call: _e.mock.On("FlashErrors", ctx, errors)}
}

func (_c *Inertia_FlashErrors_Call) Run(run func(ctx http.Context, errors validation.Errors)) *Inertia_FlashErrors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.Context), args[1].(validation.Errors))
	})
	return _c
}

func (_c *Inertia_FlashErrors_Call) Return() *Inertia_FlashErrors_Call {
	_c.Call.Return()
	return _c
}

func (_c *Inertia_FlashErrors_Call) RunAndReturn(run func(http.Context, validation.Errors)) *Inertia_FlashErrors_Call {
	_c.Run(run)
	return _c
}

// Location provides a mock function with given fields: ctx, url
func (_m *Inertia) Location(ctx http.Context, url string) http.Response {
	ret := _m.Called(ctx, url)

	if len(ret) == 0 {
		panic("no return value specified for Location")
	}

	var r0 http.Response
	if rf, ok := ret.Get(0).(func(http.Context, string) http.Response); ok {
		r0 = rf(ctx, url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Response)
		}
	}

	return r0
}

// Inertia_Location_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Location'
type Inertia_Location_Call struct {
	*mock.Call
}

// Location is a helper method to define mock.On call
//   - ctx http.Context
//   - url string
func (_e *Inertia_Expecter) Location(ctx interface{}, url interface{}) *Inertia_Location_Call {
	return &Inertia_Location_Call{Call: _e.mock.On("Location", ctx, url)}
}

func (_c *Inertia_Location_Call) Run(run func(ctx http.Context, url string)) *Inertia_Location_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.Context), args[1].(string))
	})
	return _c
}

func (_c *Inertia_Location_Call) Return(_a0 http.Response) *Inertia_Location_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Inertia_Location_Call) RunAndReturn(run func(http.Context, string) http.Response) *Inertia_Location_Call {
	_c.Call.Return(run)
	return _c
}

// Merge provides a mock function with given fields: ctx, key, fn, matchOn
func (_m *Inertia) Merge(ctx http.Context, key string, fn func() interface{}, matchOn ...string) {
	_va := make([]interface{}, len(matchOn))
	for _i := range matchOn {
		_va[_i] = matchOn[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, key, fn)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// Inertia_Merge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Merge'
type Inertia_Merge_Call struct {
	*mock.Call
}

// Merge is a helper method to define mock.On call
//   - ctx http.Context
//   - key string
//   - fn func() interface{}
//   - matchOn ...string
func (_e *Inertia_Expecter) Merge(ctx interface{}, key interface{}, fn interface{}, matchOn ...interface{}) *Inertia_Merge_Call {
	return &Inertia_Merge_Call{Call: _e.mock.On("Merge",
		append([]interface{}{ctx, key, fn}, matchOn...)...)}
}

func (_c *Inertia_Merge_Call) Run(run func(ctx http.Context, key string, fn func() interface{}, matchOn ...string)) *Inertia_Merge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(http.Context), args[1].(string), args[2].(func() interface{}), variadicArgs...)
	})
	return _c
}

func (_c *Inertia_Merge_Call) Return() *Inertia_Merge_Call {
	_c.Call.Return()
	return _c
}

func (_c *Inertia_Merge_Call) RunAndReturn(run func(http.Context, string, func() interface{}, ...string)) *Inertia_Merge_Call {
	_c.Run(run)
	return _c
}

// Once provides a mock function with given fields: ctx, key, fn
func (_m *Inertia) Once(ctx http.Context, key string, fn func() interface{}) {
	_m.Called(ctx, key, fn)
}

// Inertia_Once_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Once'
type Inertia_Once_Call struct {
	*mock.Call
}

// Once is a helper method to define mock.On call
//   - ctx http.Context
//   - key string
//   - fn func() interface{}
func (_e *Inertia_Expecter) Once(ctx interface{}, key interface{}, fn interface{}) *Inertia_Once_Call {
	return &Inertia_Once_Call{Call: _e.mock.On("Once", ctx, key, fn)}
}

func (_c *Inertia_Once_Call) Run(run func(ctx http.Context, key string, fn func() interface{})) *Inertia_Once_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.Context), args[1].(string), args[2].(func() interface{}))
	})
	return _c
}

func (_c *Inertia_Once_Call) Return() *Inertia_Once_Call {
	_c.Call.Return()
	return _c
}

func (_c *Inertia_Once_Call) RunAndReturn(run func(http.Context, string, func() interface{})) *Inertia_Once_Call {
	_c.Run(run)
	return _c
}

// Optional provides a mock function with given fields: ctx, key, fn
func (_m *Inertia) Optional(ctx http.Context, key string, fn func() interface{}) {
	_m.Called(ctx, key, fn)
}

// Inertia_Optional_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Optional'
type Inertia_Optional_Call struct {
	*mock.Call
}

// Optional is a helper method to define mock.On call
//   - ctx http.Context
//   - key string
//   - fn func() interface{}
func (_e *Inertia_Expecter) Optional(ctx interface{}, key interface{}, fn interface{}) *Inertia_Optional_Call {
	return &Inertia_Optional_Call{Call: _e.mock.On("Optional", ctx, key, fn)}
}

func (_c *Inertia_Optional_Call) Run(run func(ctx http.Context, key string, fn func() interface{})) *Inertia_Optional_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.Context), args[1].(string), args[2].(func() interface{}))
	})
	return _c
}

func (_c *Inertia_Optional_Call) Return() *Inertia_Optional_Call {
	_c.Call.Return()
	return _c
}

func (_c *Inertia_Optional_Call) RunAndReturn(run func(http.Context, string, func() interface{})) *Inertia_Optional_Call {
	_c.Run(run)
	return _c
}

// Prepend provides a mock function with given fields: ctx, key, fn, matchOn
func (_m *Inertia) Prepend(ctx http.Context, key string, fn func() interface{}, matchOn ...string) {
	_va := make([]interface{}, len(matchOn))
	for _i := range matchOn {
		_va[_i] = matchOn[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, key, fn)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// Inertia_Prepend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Prepend'
type Inertia_Prepend_Call struct {
	*mock.Call
}

// Prepend is a helper method to define mock.On call
//   - ctx http.Context
//   - key string
//   - fn func() interface{}
//   - matchOn ...string
func (_e *Inertia_Expecter) Prepend(ctx interface{}, key interface{}, fn interface{}, matchOn ...interface{}) *Inertia_Prepend_Call {
	return &Inertia_Prepend_Call{Call: _e.mock.On("Prepend",
		append([]interface{}{ctx, key, fn}, matchOn...)...)}
}

func (_c *Inertia_Prepend_Call) Run(run func(ctx http.Context, key string, fn func() interface{}, matchOn ...string)) *Inertia_Prepend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(http.Context), args[1].(string), args[2].(func() interface{}), variadicArgs...)
	})
	return _c
}

func (_c *Inertia_Prepend_Call) Return() *Inertia_Prepend_Call {
	_c.Call.Return()
	return _c
}

func (_c *Inertia_Prepend_Call) RunAndReturn(run func(http.Context, string, func() interface{}, ...string)) *Inertia_Prepend_Call {
	_c.Run(run)
	return _c
}

// PreserveFragment provides a mock function with given fields: ctx
func (_m *Inertia) PreserveFragment(ctx http.Context) {
	_m.Called(ctx)
}

// Inertia_PreserveFragment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PreserveFragment'
type Inertia_PreserveFragment_Call struct {
	*mock.Call
}

// PreserveFragment is a helper method to define mock.On call
//   - ctx http.Context
func (_e *Inertia_Expecter) PreserveFragment(ctx interface{}) *Inertia_PreserveFragment_Call {
	return &Inertia_PreserveFragment_Call{Call: _e.mock.On("PreserveFragment", ctx)}
}

func (_c *Inertia_PreserveFragment_Call) Run(run func(ctx http.Context)) *Inertia_PreserveFragment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.Context))
	})
	return _c
}

func (_c *Inertia_PreserveFragment_Call) Return() *Inertia_PreserveFragment_Call {
	_c.Call.Return()
	return _c
}

func (_c *Inertia_PreserveFragment_Call) RunAndReturn(run func(http.Context)) *Inertia_PreserveFragment_Call {
	_c.Run(run)
	return _c
}

// Prop provides a mock function with given fields: ctx, key, value
func (_m *Inertia) Prop(ctx http.Context, key string, value interface{}) {
	_m.Called(ctx, key, value)
}

// Inertia_Prop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Prop'
type Inertia_Prop_Call struct {
	*mock.Call
}

// Prop is a helper method to define mock.On call
//   - ctx http.Context
//   - key string
//   - value interface{}
func (_e *Inertia_Expecter) Prop(ctx interface{}, key interface{}, value interface{}) *Inertia_Prop_Call {
	return &Inertia_Prop_Call{Call: _e.mock.On("Prop", ctx, key, value)}
}

func (_c *Inertia_Prop_Call) Run(run func(ctx http.Context, key string, value interface{})) *Inertia_Prop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.Context), args[1].(string), args[2].(interface{}))
	})
	return _c
}

func (_c *Inertia_Prop_Call) Return() *Inertia_Prop_Call {
	_c.Call.Return()
	return _c
}

func (_c *Inertia_Prop_Call) RunAndReturn(run func(http.Context, string, interface{})) *Inertia_Prop_Call {
	_c.Run(run)
	return _c
}

// Redirect provides a mock function with given fields: ctx, url
func (_m *Inertia) Redirect(ctx http.Context, url string) http.Response {
	ret := _m.Called(ctx, url)

	if len(ret) == 0 {
		panic("no return value specified for Redirect")
	}

	var r0 http.Response
	if rf, ok := ret.Get(0).(func(http.Context, string) http.Response); ok {
		r0 = rf(ctx, url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Response)
		}
	}

	return r0
}

// Inertia_Redirect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Redirect'
type Inertia_Redirect_Call struct {
	*mock.Call
}

// Redirect is a helper method to define mock.On call
//   - ctx http.Context
//   - url string
func (_e *Inertia_Expecter) Redirect(ctx interface{}, url interface{}) *Inertia_Redirect_Call {
	return &Inertia_Redirect_Call{Call: _e.mock.On("Redirect", ctx, url)}
}

func (_c *Inertia_Redirect_Call) Run(run func(ctx http.Context, url string)) *Inertia_Redirect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.Context), args[1].(string))
	})
	return _c
}

func (_c *Inertia_Redirect_Call) Return(_a0 http.Response) *Inertia_Redirect_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Inertia_Redirect_Call) RunAndReturn(run func(http.Context, string) http.Response) *Inertia_Redirect_Call {
	_c.Call.Return(run)
	return _c
}

// Render provides a mock function with given fields: ctx, component, props
func (_m *Inertia) Render(ctx http.Context, component string, props map[string]interface{}) http.Response {
	ret := _m.Called(ctx, component, props)

	if len(ret) == 0 {
		panic("no return value specified for Render")
	}

	var r0 http.Response
	if rf, ok := ret.Get(0).(func(http.Context, string, map[string]interface{}) http.Response); ok {
		r0 = rf(ctx, component, props)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Response)
		}
	}

	return r0
}

// Inertia_Render_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Render'
type Inertia_Render_Call struct {
	*mock.Call
}

// Render is a helper method to define mock.On call
//   - ctx http.Context
//   - component string
//   - props map[string]interface{}
func (_e *Inertia_Expecter) Render(ctx interface{}, component interface{}, props interface{}) *Inertia_Render_Call {
	return &Inertia_Render_Call{Call: _e.mock.On("Render", ctx, component, props)}
}

func (_c *Inertia_Render_Call) Run(run func(ctx http.Context, component string, props map[string]interface{})) *Inertia_Render_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.Context), args[1].(string), args[2].(map[string]interface{}))
	})
	return _c
}

func (_c *Inertia_Render_Call) Return(_a0 http.Response) *Inertia_Render_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Inertia_Render_Call) RunAndReturn(run func(http.Context, string, map[string]interface{}) http.Response) *Inertia_Render_Call {
	_c.Call.Return(run)
	return _c
}

// Scroll provides a mock function with given fields: ctx, key, prop
func (_m *Inertia) Scroll(ctx http.Context, key string, prop contracts.ScrollProp) {
	_m.Called(ctx, key, prop)
}

// Inertia_Scroll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Scroll'
type Inertia_Scroll_Call struct {
	*mock.Call
}

// Scroll is a helper method to define mock.On call
//   - ctx http.Context
//   - key string
//   - prop contracts.ScrollProp
func (_e *Inertia_Expecter) Scroll(ctx interface{}, key interface{}, prop interface{}) *Inertia_Scroll_Call {
	return &Inertia_Scroll_Call{Call: _e.mock.On("Scroll", ctx, key, prop)}
}

func (_c *Inertia_Scroll_Call) Run(run func(ctx http.Context, key string, prop contracts.ScrollProp)) *Inertia_Scroll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.Context), args[1].(string), args[2].(contracts.ScrollProp))
	})
	return _c
}

func (_c *Inertia_Scroll_Call) Return() *Inertia_Scroll_Call {
	_c.Call.Return()
	return _c
}

func (_c *Inertia_Scroll_Call) RunAndReturn(run func(http.Context, string, contracts.ScrollProp)) *Inertia_Scroll_Call {
	_c.Run(run)
	return _c
}

// Share provides a mock function with given fields: key, value
func (_m *Inertia) Share(key string, value interface{}) {
	_m.Called(key, value)
}

// Inertia_Share_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Share'
type Inertia_Share_Call struct {
	*mock.Call
}

// Share is a helper method to define mock.On call
//   - key string
//   - value interface{}
func (_e *Inertia_Expecter) Share(key interface{}, value interface{}) *Inertia_Share_Call {
	return &Inertia_Share_Call{Call: _e.mock.On("Share", key, value)}
}

func (_c *Inertia_Share_Call) Run(run func(key string, value interface{})) *Inertia_Share_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(interface{}))
	})
	return _c
}

func (_c *Inertia_Share_Call) Return() *Inertia_Share_Call {
	_c.Call.Return()
	return _c
}

func (_c *Inertia_Share_Call) RunAndReturn(run func(string, interface{})) *Inertia_Share_Call {
	_c.Run(run)
	return _c
}

// ShareFunc provides a mock function with given fields: key, fn
func (_m *Inertia) ShareFunc(key string, fn func(http.Context) interface{}) {
	_m.Called(key, fn)
}

// Inertia_ShareFunc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShareFunc'
type Inertia_ShareFunc_Call struct {
	*mock.Call
}

// ShareFunc is a helper method to define mock.On call
//   - key string
//   - fn func(http.Context) interface{}
func (_e *Inertia_Expecter) ShareFunc(key interface{}, fn interface{}) *Inertia_ShareFunc_Call {
	return &Inertia_ShareFunc_Call{Call: _e.mock.On("ShareFunc", key, fn)}
}

func (_c *Inertia_ShareFunc_Call) Run(run func(key string, fn func(http.Context) interface{})) *Inertia_ShareFunc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(func(http.Context) interface{}))
	})
	return _c
}

func (_c *Inertia_ShareFunc_Call) Return() *Inertia_ShareFunc_Call {
	_c.Call.Return()
	return _c
}

func (_c *Inertia_ShareFunc_Call) RunAndReturn(run func(string, func(http.Context) interface{})) *Inertia_ShareFunc_Call {
	_c.Run(run)
	return _c
}

// ShareSession provides a mock function with given fields: ctx
func (_m *Inertia) ShareSession(ctx http.Context) {
	_m.Called(ctx)
}

// Inertia_ShareSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShareSession'
type Inertia_ShareSession_Call struct {
	*mock.Call
}

// ShareSession is a helper method to define mock.On call
//   - ctx http.Context
func (_e *Inertia_Expecter) ShareSession(ctx interface{}) *Inertia_ShareSession_Call {
	return &Inertia_ShareSession_Call{Call: _e.mock.On("ShareSession", ctx)}
}

func (_c *Inertia_ShareSession_Call) Run(run func(ctx http.Context)) *Inertia_ShareSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.Context))
	})
	return _c
}

func (_c *Inertia_ShareSession_Call) Return() *Inertia_ShareSession_Call {
	_c.Call.Return()
	return _c
}

func (_c *Inertia_ShareSession_Call) RunAndReturn(run func(http.Context)) *Inertia_ShareSession_Call {
	_c.Run(run)
	return _c
}

// URL provides a mock function with no fields
func (_m *Inertia) URL() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for URL")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Inertia_URL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'URL'
type Inertia_URL_Call struct {
	*mock.Call
}

// URL is a helper method to define mock.On call
func (_e *Inertia_Expecter) URL() *Inertia_URL_Call {
	return &Inertia_URL_Call{Call: _e.mock.On("URL")}
}

func (_c *Inertia_URL_Call) Run(run func()) *Inertia_URL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Inertia_URL_Call) Return(_a0 string) *Inertia_URL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Inertia_URL_Call) RunAndReturn(run func() string) *Inertia_URL_Call {
	_c.Call.Return(run)
	return _c
}

// Version provides a mock function with no fields
func (_m *Inertia) Version() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Version")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Inertia_Version_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Version'
type Inertia_Version_Call struct {
	*mock.Call
}

// Version is a helper method to define mock.On call
func (_e *Inertia_Expecter) Version() *Inertia_Version_Call {
	return &Inertia_Version_Call{Call: _e.mock.On("Version")}
}

func (_c *Inertia_Version_Call) Run(run func()) *Inertia_Version_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Inertia_Version_Call) Return(_a0 string) *Inertia_Version_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Inertia_Version_Call) RunAndReturn(run func() string) *Inertia_Version_Call {
	_c.Call.Return(run)
	return _c
}

// NewInertia creates a new instance of Inertia. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInertia(t interface {
	mock.TestingT
	Cleanup(func())
}) *Inertia {
	mock := &Inertia{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
